#######################
# Theme Customization #
#######################

title: systemdump
author: Xavier Lucas
description: My thoughts, technical insights and experimentations
url: https://systemdump.io
repo: https://github.com/xlucas/xlucas.github.io

baseurl: ''
banner: /images/banner.svg
avatar: /images/logo.png

disqus:
  shortname: systemdump

nav_menu:
  - name: Posts
    url: /
    icon: /images/icons.svg#posts
    icon: /images/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/xlucas
    icon: /images/icons.svg#github
    outbound: true

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
